export enum ChatAction {
  SET_STORAGE = "SET_STORAGE",
  HIDE_LOADING = "HIDE_LOADING",
  ADD_MESSAGE = "ADD_MESSAGE",
  EDIT_MESSAGE = "EDIT_MESSAGE",
  DELETE_MESSAGE = "DELETE_MESSAGE",
  TOGGLE_MODAL = "TOGGLE_MODAL",
  SET_INITIAL = "SET_INITIAL",
  TOGGLE_MODAL_ON_KEY = "TOGGLE_MODAL_ON_KEY",
}
