export enum ChatAction {
  ADD_MESSAGE = "ADD_MESSAGE",
  EDIT_MESSAGE = "EDIT_MESSAGE",
  DELETE_MESSAGE = "DELETE_MESSAGE",
  CHANGE_LIKE = "CHANGE_LIKE",
  HIDE_LOADING = "HIDE_LOADING",
  INIT_STORAGE = "INIT_STORAGE"
}
